services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: follow-de-roadmap
    ports:
      - 5432:5432
      
  python3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  
  
    